version: '3'
services:
    db:
      container_name: postgres
      image: postgres:10.3
      environment:
        POSTGRES_PASSWORD: password123
      restart: always
      ports:
        - "5432:5432"
      volumes:
        - ./database:/var/lib/postgresql/data/
        - ./config/postgres/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        - ./config/postgres/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
        
    nginx:
        container_name: nginx
        image: nginx:1.13.12
        restart: always
        command: nginx -g "daemon off;"
        ports:
        - "80:80" 
        volumes:
        - ./source:/www/project/
        - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
        - django
        
    django:
        container_name: django
        image: phishion/django
        restart: always
        command: uwsgi  --emperor /uwsgi.ini
        ports:
        - "8000:8000"
        - "8080:8080"
        volumes:
        - ./source:/www/project/
        - ./config/django/uwsgi.ini:/uwsgi.ini
        depends_on:
        - db
